### ISSUE TITLE
Running `ember test` on a Glimmer App breaks if run on BashOnWindows

### ISSUE THREAD

**Issue by andreisebastianc** [glimmerjs/glimmer-application#95]
I know this is probably not a top priority, but in the Ubuntu Bash on Windows I keep getting:
```
Built project successfully. Stored in "/mnt/c/Users/acimpean/Documents/projects/glimmer-weco-demo/tmp/class-tests_dist-etgV96Ai.tmp".
not ok 1 Error
    ---
        message: >
            Launcher Chrome not found. Not installed?
```

This is happening because Chrome can't be accessed in that context. There's a whole discussion about this on this Microsoft github issue https://github.com/Microsoft/BashOnWindows/issues/648 and that might be a solution.

However, running tests on an Ember App in BashOnWindows works just fine, I imagine because it can either use phantomjs (enough 99% of the time in my experience) or start a server and connect to it with Chrome.

**Comment by robbiepitts** [comment]
Thank you for reporting! I think you can fix this by making PhantomJS the launcher in your `testem.json`:

```
{
  "framework": "qunit",
  "src_files": ["src/**/*"],
  "serve_files": ["index.js"],
  "disable_watching": true,
  "launch_in_ci": ["PhantomJS"]
}
```

Not sure what we want to do to make this a better DX out of the box though. I will let others chime in.

**Comment by rwjblue** [comment]
@robbiepitts - I don't think we (Glimmer.js) support `phantomjs`....

**Comment by andreisebastianc** [comment]
Well, there are other problems it seems with trying PhantomJS with BashOnWindows.
Maybe headless chrome ? I'll give it a try.

```
andrei@glimmer-weco-demo$ember test
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
⠙ Building/src/ui/components/bar-chart/component.ts(3,29): Property 'd3' does not exist on type 'Window'.
/src/ui/components/bar-chart/component.ts(21,40): Property 'querySelector' does not exist on type 'Element'.
cleaning up...
Built project successfully. Stored in "/mnt/c/Users/acimpean/Documents/projects/glimmer-weco-demo/tmp/class-tests_dist-0FpaHP8g.tmp".
not ok 1 PhantomJS - error
    ---
        message: >
            Error: Browser exited unexpectedly
            Non-zero exit code: null
            Stderr:
             QXcbConnection: Could not connect to display
            PhantomJS has crashed. Please read the bug reporting guide at
            <http://phantomjs.org/bug-reporting.html> and file a bug report.


        Log: |
            { type: 'error', text: 'Error: Browser exited unexpectedly' }
            { type: 'error', text: 'Non-zero exit code: null' }
            { type: 'error',
              text: 'QXcbConnection: Could not connect to display \nPhantomJS has crashed. Please read the bug reporting guide at\n<http://phantomjs.org/bug-reporting.html> and file a bug report.\n' }
    ...

1..1
# tests 1
# pass  0
# skip  0
# fail  1
```

**Comment by andreisebastianc** [comment]
I tried running the tests in PowerShell.
The dummy app loads in the browser, and works. I removed everything from `tmp` before building.

```
PS C:\Users\acimpean\Documents\projects\glimmer-weco-demo> ember build

Running without permission to symlink will degrade build performance.
See http://ember-cli.com/user-guide/#windows for details.

\ Building/src/ui/components/bar-chart/component.ts(3,29): Property 'd3' does not exist on type 'Window'.
/src/ui/components/bar-chart/component.ts(21,40): Property 'querySelector' does not exist on type 'Element'.
cleaning up...
Built project successfully. Stored in "dist/".
PS C:\Users\acimpean\Documents\projects\glimmer-weco-demo> ember test

Running without permission to symlink will degrade build performance.
See http://ember-cli.com/user-guide/#windows for details.

\ Building/src/ui/components/bar-chart/component.ts(3,29): Property 'd3' does not exist on type 'Window'.
/src/ui/components/bar-chart/component.ts(21,40): Property 'querySelector' does not exist on type 'Element'.
cleaning up...
Build failed.
Build Canceled: Broccoli Builder ran into an error with RollupWithDependencies plugin. 💥
C:/Users/acimpean/Documents/projects/glimmer-weco-demo/tmp/rollup_with_dependencies-cache_path-F2fjOehx.tmp/tests.js: Bad character escape sequence (1:15)
Error: C:/Users/acimpean/Documents/projects/glimmer-weco-demo/tmp/rollup_with_dependencies-cache_path-F2fjOehx.tmp/tests.js: Bad character escape sequence (1:15)
    at error (C:\Users\acimpean\Documents\projects\glimmer-weco-demo\node_modules\rollup\dist\rollup.js:170:12)
    at C:\Users\acimpean\Documents\projects\glimmer-weco-demo\node_modules\rollup\dist\rollup.js:8937:6
PS C:\Users\acimpean\Documents\projects\glimmer-weco-demo> ls .\tmp\
PS C:\Users\acimpean\Documents\projects\glimmer-weco-demo> ember s

Running without permission to symlink will degrade build performance.
See http://ember-cli.com/user-guide/#windows for details.

Livereload server on http://localhost:49153
/src/ui/components/bar-chart/component.ts(3,29): Property 'd3' does not exist on type 'Window'.
/src/ui/components/bar-chart/component.ts(21,40): Property 'querySelector' does not exist on type 'Element'.

Build successful (65264ms) – Serving on http://localhost:4200/



Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
BroccoliMergeTrees (9)                        | 59313ms (6590 ms)
RollupWithDependencies (1)                    | 3898ms
```

Any ideas? At the moment it seems that I can't run tests on Windows.

**Comment by codewarrior415** [comment]
I added this and it worked.
"--no-sandbox",
"--user-data-dir=/tmp"
`
/* eslint-env node */
module.exports = {
  test_page: 'tests/index.html?hidepassed',
  disable_watching: true,
  launch_in_ci: [
    'Chrome'
  ],
  launch_in_dev: [
    'Chrome'
  ],
  browser_args: {
    Chrome: {
      mode: 'ci',
      args: [
        '--disable-gpu',
        '--headless',
        '--remote-debugging-port=0',
        '--window-size=1440,900',
        "--no-sandbox",
        "--user-data-dir=/tmp"
      ]
    }
  }
};

`

**Comment by locks** [comment]
This repo has been merged with [glimmerjs/glimmer.js](https://github.com/glimmerjs/glimmer.js) (into a monorepo setup). I am not sure if this issue is still applicable, but if you could confirm it is still an ongoing concern and open it over there that would be very helpful.

Sorry for the noise, but thank you for your help!
